Nombre1 = float(input("Entrer un nombre : "))
Nombre2 = float(input("Entrer un nombre : "))
Nombre3 = float(input("Entrer un nombre : "))
plus_grand_nombre = max(Nombre1, Nombre2, Nombre3)
print(f"Le plus grand nombre est :" ,plus_grand_nombre,)